version: '3'

services:

  database:
    container_name: database
    image: mysql:5.7.19 ## mysql:8.0.29-oracle #mysql:5.7
    restart: always
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=sePret^i
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=password
    hostname: mysqldatabase
    ports:
      - 3306:3306
  
  todo_app:
    container_name: todo_app
    build: .
    restart: always
    depends_on:
      - database
    environment:
      - DB_HOST=test
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=sePret^i
    ports:
      - 80:80
    # env_file:
    #   - .env.sample
    